### ISSUE TITLE
Error in computation of SSA part of the Synchr. spectrum

### ISSUE THREAD

**Issue by jsitarek** [cosimoNigro/agnpy#41] opened 2020-08-06 09:36 UTC
The changes made in the class since May somehow broke the way how synchrotron spectrum is calculated. Please find attached a notebook where I compare the old and new version and plot also a theoretical line
[validate_synchr.ipynb.gz](https://github.com/cosimoNigro/agnpy/files/5033975/validate_synchr.ipynb.gz)

**Comment by cosimoNigro** [comment] 2020-08-06 09:44
Hi @jsitarek, thanks for reporting this, I check the SSA for the `PowerLaw` case in the test, comparing the SED with one I generated in a previous version of the code:
https://github.com/cosimoNigro/agnpy/blob/master/agnpy/tests/test_synchrotron.py#L111
I think the problem is related only to the `BrokenPowerLaw`, the analytical formula I have used might be incorrect, with respect to the previous version. I am sure the problem is there, will check! 
Thank you!

**Comment by jsitarek** [comment] 2020-08-06 10:14
looking through the code, I got a similar conclusion, the SSA integrant function for the broken PWL has changed considerably between the two versions of the code, but since it is pretty complicated, I prefer not to touch it myself, so if you can fix it, it would be great. 

I checked also the PWL and LP, for PWL both old and new code indeed gives the same result, LP was not supported in the old code. Both PWL and LP however give me somewhat different values then theoretical curve, in particular if gamma_min is >>1: 
![lp_test](https://user-images.githubusercontent.com/33022433/89520150-b73a0a80-d7dd-11ea-91bc-bdfdd25506de.png)
![pwl_test](https://user-images.githubusercontent.com/33022433/89520355-03854a80-d7de-11ea-929e-e7aa442a1912.png)
For this simple test I calculate this SSA from effective temperature of electrons, see e.g.: https://www.cv.nrao.edu/course/astr534/SelfAbsorption.html while you do the full absorption calculations, but still it is somewhat suspicious, so it would be great if you have a look at the other two integrants as well if there is no similar mistake there.

**Comment by cosimoNigro** [comment] 2020-09-14 10:01
Hi @jsitarek,
I solved this with PR #43 and introduced some tests against SSA SEDs generate with `jetset` (check the figures in the pull request).
I am closing this.

**Closed by cosimoNigro** 2020-09-14 10:01 UTC
Labels: bug
